import { readFile } from 'node:fs/promises'
import type { Page } from '@playwright/test'
import { test, expect, catalogFixture, fullTableNames, readState, restoreViaUI, startTrip, selectCatalog, saveCatch } from './fixtures'

const modal = (page: Page) => page.getByRole('dialog', { name: '釣果を登録', exact: true })
const home = (page: Page) => page.getByRole('button', { name: '← ホーム', exact: true }).click()
async function open(page: Page) {
  await page.getByRole('button', { name: '🎣 釣れた！', exact: true }).click()
  await expect(modal(page).getByRole('combobox', { name: '魚種を選択', exact: true })).toHaveValue('F001')
  await expect(modal(page).getByLabel('全長（cm・任意）', { exact: true })).toHaveValue('')
}
async function chooseFish(page: Page, name: string, id: string, size?: string) {
  await modal(page).getByLabel('魚種を検索', { exact: true }).fill(name)
  await modal(page).getByRole('combobox', { name: '魚種を選択', exact: true }).selectOption(id)
  if (size) await modal(page).getByLabel('全長（cm・任意）', { exact: true }).fill(size)
}

async function prepareFishHistory(page: Page) {
  await restoreViaUI(page, catalogFixture()) // 旧v4から開始、魚種を旧釣果へ割り当てない。
  await page.getByRole('button', { name: '魚種マスター管理', exact: true }).click()
  await page.getByRole('button', { name: '初期魚種37件を登録', exact: true }).click()
  await expect(page.getByRole('heading', { name: '魚種一覧（37件）', exact: true })).toBeVisible()
  let data = await readState(page)
  expect(data.fishSpecies.filter(row => row.group === 'ニジマス')).toHaveLength(1)
  expect(data.fishSpecies.filter(row => row.group === 'イロモノ')).toHaveLength(15)
  expect(data.fishSpecies.filter(row => row.group === 'ブランドマス')).toHaveLength(21)
  expect(data.fishSpecies.some(row => row.fish_id === 'F017')).toBe(false)
  await page.getByRole('button', { name: '初期魚種37件を登録', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('0件追加')
  expect(await readState(page)).toEqual(data)
  await page.getByLabel('表示名（必須）', { exact: true }).fill('E2E独自ブランド')
  await page.getByLabel('地域', { exact: true }).fill('合成県')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('heading', { name: '魚種一覧（38件）', exact: true })).toBeVisible()
  data = await readState(page)
  const userId = data.fishSpecies.find(row => row.display_name === 'E2E独自ブランド')!.fish_id
  expect(userId).toMatch(/^user:/)
  await page.getByRole('button', { name: '← 戻る', exact: true }).click()
  await startTrip(page)
  await open(page)
  await selectCatalog(page)
  await chooseFish(page, 'ハコスチ', 'F020', '50.5')
  await saveCatch(page)
  await open(page)
  await selectCatalog(page)
  await chooseFish(page, 'イワナ', 'F006', '22')
  await saveCatch(page)
  await open(page)
  await modal(page).getByRole('button', { name: '前回と同じ' }).click()
  await expect(modal(page)).not.toBeVisible()
  data = await readState(page)
  expect(data.catches[0]).toMatchObject({ fishSpeciesId: 'F020', fishSpecies: 'ハコスチ', fishSpeciesGroup: 'ブランドマス', fishSizeCm: 50.5 })
  expect(data.catches[1]).toMatchObject({ fishSpeciesId: 'F006', fishSpecies: 'イワナ', fishSpeciesGroup: 'イロモノ', fishSizeCm: 22 })
  expect(data.catches[2]).toMatchObject({ fishSpeciesId: 'F006', fishSpecies: 'イワナ', fishSpeciesGroup: 'イロモノ' })
  expect(data.catches[2]).not.toHaveProperty('fishSizeCm')
  await open(page)
  await selectCatalog(page)
  await chooseFish(page, 'E2E独自ブランド', userId, '32.5')
  await saveCatch(page)
  const beforeEdit = (await readState(page)).catches
  await home(page)
  await page.getByRole('button', { name: '魚種マスター管理', exact: true }).click()
  const list = page.getByRole('region', { name: '魚種一覧' })
  await list.getByRole('combobox', { name: '分類で絞り込み', exact: true }).selectOption('ブランドマス')
  await list.getByLabel('名称検索', { exact: true }).fill('E2E独自ブランド')
  const article = list.getByRole('article')
  await expect(article).toHaveCount(1)
  await expect(article).toContainText('ユーザー登録')
  await article.getByRole('button', { name: '編集', exact: true }).click()
  await page.getByLabel('表示名（必須）', { exact: true }).fill('E2E独自ブランド改名')
  await page.getByRole('combobox', { name: '表示分類', exact: true }).selectOption('イロモノ')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('魚種を保存しました')
  expect((await readState(page)).catches).toEqual(beforeEdit)
  await page.getByRole('button', { name: '初期魚種37件を登録', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('0件追加')
  expect((await readState(page)).fishSpecies.find(row => row.fish_id === userId)!.display_name).toBe('E2E独自ブランド改名')
  await page.getByRole('button', { name: '← 戻る', exact: true }).click()
  await page.getByRole('button', { name: /E2Eニレ池/ }).click()
  const history = page.getByRole('region', { name: '釣果履歴' })
  await expect(history).toContainText('ハコスチ（ブランドマス） / 50.5cm')
  await expect(history).toContainText('イワナ（イロモノ） / 22cm')
  await expect(history).toContainText('E2E独自ブランド（ブランドマス） / 32.5cm')
  await expect(history).not.toContainText('E2E独自ブランド改名')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  return await readState(page)
}

test('E: 初期37種・ニジマス初期選択・ハコスチ/イワナ/独自ブランド・前回魚種とサイズ非継承・履歴不変', async ({ page }) => {
  await prepareFishHistory(page)
  await open(page)
  await modal(page).getByRole('combobox', { name: '魚種を選択', exact: true }).selectOption('')
  await saveCatch(page)
  await open(page)
  await modal(page).getByRole('button', { name: '前回と同じ' }).click()
  await expect(modal(page)).not.toBeVisible()
  const data = await readState(page)
  expect(data.catches).toHaveLength(6)
  for (const row of data.catches.slice(4)) {
    expect(row).not.toHaveProperty('fishSpeciesId')
    expect(row).not.toHaveProperty('fishSpecies')
  }
  await expect(page.getByRole('region', { name: '釣果履歴' })).toContainText('魚種未設定')
})

test('F: v5全13テーブルのダウンロードと別Context復元で魚種・サイズ・スナップショットを保持', async ({ page, browser }, testInfo) => {
  const source = await prepareFishHistory(page)
  await home(page)
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: '📦 データをバックアップ', exact: true }).click()
  const download = await pending
  const path = testInfo.outputPath('synthetic-v5-fish-backup.json')
  await download.saveAs(path)
  const value = JSON.parse(await readFile(path, 'utf8'))
  expect(value.version).toBe(5)
  expect(value.format).toBe('fishing-log-backup')
  expect(Object.keys(value.data).sort()).toEqual([...fullTableNames].sort())
  expect(value.data).toEqual(source)
  const context = await browser.newContext({ viewport: page.viewportSize()!, isMobile: !!testInfo.project.use.isMobile,
    hasTouch: !!testInfo.project.use.hasTouch, locale: 'ja-JP', timezoneId: 'Asia/Tokyo', serviceWorkers: 'block' })
  try {
    const restored = await context.newPage()
    const errors: string[] = []
    restored.on('pageerror', error => errors.push(error.message))
    await restored.route('**/*', route => new URL(route.request().url()).origin === 'http://127.0.0.1:4177' ? route.continue() : route.abort())
    await restored.goto('http://127.0.0.1:4177')
    await expect(restored.getByRole('heading', { name: '🎣 Fishing Log', exact: true })).toBeVisible()
    expect(Object.values(await readState(restored)).every(rows => rows.length === 0)).toBe(true)
    await restoreViaUI(restored, value)
    expect(await readState(restored)).toEqual(source)
    await restored.getByRole('button', { name: /E2Eニレ池/ }).click()
    await expect(restored.getByRole('region', { name: '釣果履歴' })).toContainText('E2E独自ブランド（ブランドマス） / 32.5cm')
    expect(await readState(page)).toEqual(source)
    expect(errors).toEqual([])
  } finally { await context.close() }
})
